exa-analytics/exatomic

- atomic/__init__.py
- atomic/install.py
- atomic/molecule.py
- atomic/one.py
- atomic/tools.py
- atomic/two.py
- atomic/universe.py
- atomic/xyz.py
- setup.py
Please take a look at the reworked read_xyz function; I think we should discuss.
> Start of the atomic container

- atomic/__init__.py
- atomic/algorithms/__init__.py
- atomic/algorithms/packing.py
- atomic/algorithms/pcf.py
- atomic/atom.py
- atomic/formula.py
- atomic/frame.py
- atomic/molecule.py
- atomic/scf.py
- atomic/static/nbextensions/threejs.js
- atomic/static/nbextensions/universe.js
- atomic/two.py
- atomic/universe.py
- atomic/xyz.py
- doc/source/api.rst
- doc/source/atom.rst
- doc/source/dataframes.rst
- doc/source/utilities.rst
Rendering updates
Start of molecule calculation
> Free boundary conditions two body props

- atomic/algorithms/__init__.py
- atomic/algorithms/pcf.py
- atomic/atom.py
- atomic/frame.py
- atomic/static/nbextensions/threejs.js
- atomic/static/nbextensions/universe.js
- atomic/two.py
- atomic/universe.py
- atomic/xyz.py
> Switch from objects to categories in DF dtypes

- atomic/atom.py
- atomic/field.py
- atomic/filetypes/cube.py
- atomic/nbextensions/app.js
- atomic/nbextensions/gto.js
- atomic/nbextensions/test.js
- atomic/nbextensions/universe.js
- atomic/two.py
- atomic/universe.py
Also reverted gv() in app.js and updated a gto function.
> Finished saving and loading; working on concatenation and field addition

- atomic/atom.py
- atomic/filetypes/cube.py
- atomic/nbextensions/app.js
- atomic/nbextensions/field.js
- atomic/nbextensions/universe.js
- atomic/universe.py
Try it out:
```
cube = atomic.Cube('ecp-pbe-19.cube')
u0 = cube.to_universe()
cube = atomic.Cube('ecp-pbe-20.cube', label='20')
u1 = cube.to_universe()
u0.add_field(u1.field)
u0
```
> Preliminary support for render cube file fields in the notebook extension.

- atomic/__init__.py
- atomic/atom.py
- atomic/error.py
- atomic/formula.py
- atomic/frame.py
- atomic/molecule.py
- atomic/two.py
- atomic/universe.py
Should help with situations where one uses a single type of ghost atom (can have any number of ghost atoms, but no support for disambiguation of them yet).
> Added default ghost atom

- atomic/filetypes/xyz.py
- atomic/nbextensions/app.js
- atomic/nbextensions/field.js
- doc/source/modules/atom.rst
- doc/source/modules/filetypes.rst
- setup.py
Also implements basics of write_xyz.
> Fixed a bug on selecting frames using the dropdown menu

- doc/source/conf.py
- exatomic/__init__.py
- exatomic/_config.py
- exatomic/_nbextension/app.js
- exatomic/widget.py
- requirements.txt
Also attempts to workaround rtd issues
> Fixes config scope

- exatomic/algorithms/distance.py
- exatomic/algorithms/neighbors.py
- exatomic/container.py
- exatomic/molecule.py
> Adds in basic support for nearest neighbor searches

- exatomic/__init__.py
- exatomic/algorithms/diffusion.py
- exatomic/atom.py
- exatomic/container.py
- meta.yaml
Also fixes saving the atom table when labels are present.
> Sets up a new paradigm for setting _traits_need_update

- exatomic/widgets/widget.py
Just forgot to remove some old left over code that got flagged as a conflict.
> Removed an unresolved HEAD from widget.py line 349.

- exatomic/core/two.py
- exatomic/interfaces/xyz.py
Fixed SettingWithCopy warning in atom_two bonds and fixed XYZ.write typo.
> Fixed a couple of last bugs for release

- README.md
- exatomic/adf/output.py
- exatomic/algorithms/basis.py
- exatomic/algorithms/orbital.py
- exatomic/core/universe.py
- exatomic/nbo/output.py
Only parses momatrix, not the lmo orbital table. Does not parse other contributions.
> Added localized momatrix parsing for ADF

- .travis.yml
- docs/source/api/base.rst
- docs/source/api/index.rst
- docs/source/notebooks/qe.ipynb
And updated the QE notebook example.
> Updated documentation for resource and list resources

- .travis.yml
- appveyor.yml
- build.sh
- docs/source/api/algorithms/neighbors.rst
- exatomic/_version.py
- exatomic/algorithms/neighbors.py
- exatomic/core/basis.py
- exatomic/core/tests/test_basis.py
- exatomic/interfaces/tests/test_cube.py
- exatomic/interfaces/xyz.py
- meta.yaml
Added a function for nearest neighbor selection on large (~10k) atom/frame universes. Updated documentation and silenced some pandas warnings (applicable to pandas version >0.21 - maintains existing behavior but suppresses warnings).
> Update to version 0.4.1

- exatomic/widgets/widget.py
Just had to uncomment two vars in the TensorContainer that are required.
This closes #127
> Fixing tensor container

- exatomic/algorithms/diffusion.py
> corrected unit conversion in diffusion.einstein_relation

- .travis.yml
- appveyor.yml
- exatomic/core/atom.py
- exatomic/core/tensor.py
- exatomic/core/tests/test_atom.py
- exatomic/gaussian/output.py
- exatomic/gaussian/tests/test_output.py
- exatomic/nwchem/output.py
- exatomic/plotter/__init__.py
- exatomic/plotter/plot.py
- exatomic/va/inputs.py
- requirements.txt
This is meant to be the initial code to address issue #155. I added a plotter directory that will have a few base classes that can be used to generate some plots. I have done this for bokeh, but I left in some code that I made up for matplotlib with the thought that it might be useful to have both.
The following code can be used to test the code
```
from exatomic.base import resource
from exatomic import gaussian
freq = gaussian.Output(resource("g16-methyloxirane-def2tzvp-freq.out"))
nmr = gaussian.Output(resource("g16-nitromalonamide-6-31++g-nmr.out"))
freq.parse_frequency()
nmr.parse_nmr_shielding()
freq.frequency.ir_spectra(lineshape='gaussian', fwhm=15)
nmr.nmr_shielding.nmr_spectra(fwhm=1, lineshape='lorentzian', atom='H')
```
> IR and NMR plotting

- exatomic/core/atom.py
- exatomic/core/tests/test_atom.py
Fixing the bug found. Compared this to avogadro and a calculation by hand on excel.
Will close #163
> Fixing bug in rotation of molecule

- .travis.yml
Small PR to get coveralls back and working
Closes #177
> Testing something to get travis to send coverage report

- exatomic/va/inputs.py
- exatomic/va/tests/test_inputs.py
Closes #171.
Changed to a 0 based index to remain consistent to python indexing.
> Changing to a 0 based index for va displaced index generator

- exatomic/__init__.py
- js/package.json
- js/src/notebook.js
- js/webpack.config.js
Logged in with an npm user via the CLI; merely ran the command
```bash
npm publish
```
with the updated webpack config. Should be possible to add to automation.
> publishes js

- js/package.json
- js/src/base.js
- js/webpack.config.js
Mainly just updated class definitions and stripped semicolons at the end of lines.
> Syntax update for js/src/base.js

- .travis.yml
- js/package.json
Already closed but Closes #190
> Automates npm publish

- exatomic/core/basis.py
- exatomic/core/orbital.py
- exatomic/core/tests/test_basis.py
- exatomic/molcas/output.py
- exatomic/widgets/traits.py
Closes #204 
This PR makes the tests pass but I'm concerned that our copious use of pandas indexes in various forms and lack of sufficient test coverage will inevitably introduce bugs into the repository. However, we do need to update our internal API to support modern versions in the ecosystem.
> Fixes tests with pandas 1.3.4

- exatomic/core/orbital.py
> Bug with pandas pivot fixed
